plugins { alias(libs.plugins.kotlin.jvm) }
kotlin { compilerOptions { jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17 } }
tasks.withType(JavaCompile).configureEach { sourceCompatibility = '17'; targetCompatibility = '17' }
dependencies { implementation libs.re2j; testImplementation libs.junit }
