[versions]
agp = "8.11.2"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.28"
compose = "2025.04.01"
room = "2.7.1"
[libraries]
junit = { module = "junit:junit", version = "4.13.2" }
re2j = { module = "com.google.re2j:re2j", version = "1.8" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
activity-compose = { module = "androidx.activity:activity-compose", version = "1.10.1" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
work-runtime = { module = "androidx.work:work-runtime-ktx", version = "2.10.1" }
gson = { module = "com.google.code.gson:gson", version = "2.13.1" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.9.0" }
test-runner = { module = "androidx.test:runner", version = "1.6.2" }
test-junit = { module = "androidx.test.ext:junit", version = "1.2.1" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
